import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster position="top-left" />
        <Toaster toasterId="your-turn" containerStyle={
          {
            position: "fixed",
            top: "10vh",
            left: "40vw",
            right: "auto",
            bottom: "auto",
          }
        } toastOptions={{
          style: {
            fontSize: "18px",
            padding: "16px 20px",
            minWidth: "360px",
            borderRadius: "14px",
          },
        }} />
      </body>
    </html>
  );
}
